apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.44.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 9121
        env:
        - name: REDIS_ADDR
          value: "redis://redis:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: prod
spec:
  selector:
    app: redis-exporter
  ports:
  - port: 9121
    targetPort: 9121
