# Prometheus 配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prod
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'backend'
        static_configs:
          - targets: ['backend:8000']
      - job_name: 'redis'
        static_configs:
          - targets: ['redis-exporter:9121']
      - job_name: 'mysql'
        static_configs:
          - targets: ['mysql-exporter:9104']
