apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter:v0.13.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 9104
        env:
        - name: MYSQL_EXPORTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-exporter-secret
              key: password
        - name: DATA_SOURCE_NAME
          value: "exporter:$(MYSQL_EXPORTER_PASSWORD)@(mysql:3306)/"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: dev
spec:
  selector:
    app: mysql-exporter
  ports:
  - port: 9104
    targetPort: 9104