apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dev
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 8000
    targetPort: 8000
  type: NodePort