apiVersion: v1
kind: Service
metadata:
  name: mysql    # 这个名字要和代码中的 MYSQL_HOST 环境变量匹配
  namespace: prod
spec:
  selector:
    app: database    # 注意这里要匹配我们之前给 MySQL StatefulSet 设置的标签
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
